package org.example.Example;


/**
* Example/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, September 5, 2024 11:20:17 PM ICT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
